# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('users_messages', '0002_auto_20171122_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(related_name='messages', to='login_registration.User'),
        ),
    ]
