# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0003_auto_20171123_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ManyToManyField(related_name='comments', to='users_messages.Message'),
        ),
    ]
