# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0004_auto_20171123_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users_messages.Message'),
            preserve_default=False,
        ),
    ]
