# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0005_comment_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_id',
            field=models.IntegerField(default=0),
        ),
    ]
